# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f1ec96d61e91c6398266a51e9f311f280474c3a0634553afacdbfce9e7c6518eaf3f8a8a0632ac63e2c56beefcc99a91264596c59a33310deb712b9f5898259

test:
  secret_key_base: fe0de9972eaa68fc88377ae4c39abb134da2cab8891511994bece9274cfebde49c4040687d38c0e2641c6c7a1d7ed6500ec060df75278aa7c5abc0ce960ad7f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
